version: 0.0
os: linux
files:
  - source: /build
    destination: /home/ubuntu/findTutorFrontEnd/build
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root

